version: '3.8'
services:
  demonstration:
    build: .
    restart: always
    container_name: obs-demonstration
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app
    env_file: 
      - .env
