version: '3.0'
services:
  dev:
    build: .
    restart: always
    container_name: obs-demo
    ports:
      - '80:3000'
    volumes:
      - ./:/usr/app
    environment:
      - REDIS_HOST=obsidian-demo-redis-cache.ovga9a.0001.use1.cache.amazonaws.com
      - PG_PORT=${RDS_PORT}
      - PG_USER=${RDS_USERNAME}
      - PG_DATABASE=${RDS_DB_NAME}
      - PG_PASSWORD=${RDS_PASSWORD}
      - PG_HOSTNAME=${RDS_HOSTNAME}
